# Generated by Django 4.1.2 on 2022-10-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0002_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="task_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
