# Generated by Django 4.1.2 on 2022-10-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0005_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="task_status",
            field=models.CharField(
                choices=[("AC", "Active"), ("CO", "Completed")],
                default="AC",
                max_length=2,
            ),
        ),
    ]
