# Generated by Django 4.1.2 on 2022-10-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0006_tasks_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="profilepic",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
