# Generated by Django 4.1.2 on 2022-11-11 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0008_alter_userdata_profilepic_alter_userdata_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labels", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="images")),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 11, 13, 46, 16, 628111)
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.userdata",
                    ),
                ),
            ],
        ),
    ]
