# Generated by Django 4.1.2 on 2022-11-11 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0009_photodata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photodata",
            name="upload_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 11, 15, 1, 1, 475689)
            ),
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
                (
                    "photo_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.photodata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phototag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.photodata",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authenticate.tags",
                    ),
                ),
            ],
        ),
    ]
