# Generated by Django 4.1.2 on 2022-11-11 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0010_alter_photodata_upload_date_tags_phototag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tags",
            name="photo_data",
        ),
        migrations.AlterField(
            model_name="photodata",
            name="upload_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 11, 15, 4, 16, 94443)
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
