# Generated by Django 4.1.2 on 2022-11-12 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authenticate",
            "0011_remove_tags_photo_data_alter_photodata_upload_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photodata",
            name="labels",
        ),
        migrations.AlterField(
            model_name="photodata",
            name="upload_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 11, 19, 32, 37, 497804)
            ),
        ),
    ]
